### PR TITLE
daizha.html

### PR DESCRIPTION
**Pull request by DaizhaNorris**
hello world

### CODE REVIEW

**Comment by DaizhaNorris** [comment]
Hm, I think I did it. Can you check

**Comment by yanamal** [comment]
That looks better now - puzzle.html is correct, but can you now delete the old ones? ("puzzle" without the .html, and "daizha.html"), and preferably also .DS_store, but that one can be harder to find and delete)

I'm going off of what I see here, by the way: https://github.com/yanamal/html-hax/pull/15/files

**Comment by yanamal** [comment]
Oh, almost forgot - can you also change the contents of the <title> tag to be a different title than the other puzzle?

**Comment by DaizhaNorris** [comment]
Okay got it.

**Pull request merged**
